/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define ADC1_BASE_ADDR		0x40012000UL
#define ADC1_CR1_OFFSET		0x04UL
#define ADC1_CR1_REG_ADDR	(ADC1_BASE_ADDR + ADC1_CR1_OFFSET)

#define RCC_BASE_ADDR			0x40023800UL
#define RCC_APB2ENR_OFFSET		0x44
#define RCC_APB2ENR_REG_ADDR	(RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)

int main(void) {
	//1. Enable the clock for ADC1 peripheral first
	uint32_t *pRcc_Apb2enr = (uint32_t*)RCC_APB2ENR_REG_ADDR;
	*pRcc_Apb2enr = (1 << 8);
	//2. set the SCAN bit in ADC1 CR1 register
	uint32_t *pAdc_Cr1 = (uint32_t*)ADC1_CR1_REG_ADDR;
	*pAdc_Cr1 |= (1 << 8);
}
